hiba javítások
Sboti03/se-lab pull request #1
Opened 2024-10-16 13:30 UTC by Sboti03

2024-10-16 14:37 UTC, BLevi73 requested changes

2024-10-16 14:37 UTC, BLevi73 commented on src/main/java/hu/bme/mit/spaceship/TorpedoStore.java
> +      this.torpedoCount -= numberOfTorpedos;
this.torpedoCount -= numberOfTorpedos helyett használd azt hogy this.torpedoCount = this.torpedoCount - numberOfTorpedos

2024-10-16 14:43 UTC, BLevi73 approved these changes
Tökéletes

2025-03-22 17:10 UTC, Sboti03 reviewed
Biztos jo

2025-03-22 17:10 UTC, merged